repository_type: pipeline
#lint:
#  files_exist:
#    - lib/nfcore_external_java_deps.jar
#    - conf/modules.config
#  actions_awsfulltest: false
#  modules_config: false
nf_core_version: 3.3.2
template:
  author: Edoardo Giuili
  description: DecoNFlow is a bioinformatics analysis pipeline used for
    computational deconvolution of DNA methylation data.
    It allows deconvolution of samples using both reference-based and
    reference-free deconvolution tools.
  force: false
  is_nfcore: true
  name: DecoNFlow
  org: TOBI lab
  outdir: .
  version: 2.3.0
