#input: ../resources/reference.csv
outdir: ../results4
test_set: ../resources/test.csv
regions: ../resources/RRBS_regions20-200.bed
#test_bams: ./assets/test_bam.csv
#fasta: /Users/edoardogiuili/Library/CloudStorage/OneDrive-UGent/Projects/Maisa_deconv_benchmark/test-datasets/hg19.fa.gz
#uxm_atlas: ./assets/Atlas.l3.tsv
#uxm: true
#methyl_atlas: true
#DMRselection: DSS
#ref_bams: /Users/edoardogiuili/Library/CloudStorage/OneDrive-UGent/Projects/Maisa_deconv_benchmark/DNAmDeconv/assets/ref_bam.csv
#groups_file: /Users/edoardogiuili/Library/CloudStorage/OneDrive-UGent/Projects/Maisa_deconv_benchmark/DNAmDeconv/assets/groups.csv