#input: assets/reference.csv
outdir: ../results5
#test_set: assets/test.csv
test_bams: ./assets/test_bam.csv
fasta: /Users/edoardogiuili/Library/CloudStorage/OneDrive-UGent/Projects/Maisa_deconv_benchmark/test-datasets/hg19.fa.gz
uxm_atlas: ./assets/Atlas.l3.tsv
uxm: true
DMRselection: wgbstools
#ref_bams: /Users/edoardogiuili/Library/CloudStorage/OneDrive-UGent/Projects/Maisa_deconv_benchmark/DNAmDeconv/assets/ref_bam.csv
#groups_file: /Users/edoardogiuili/Library/CloudStorage/OneDrive-UGent/Projects/Maisa_deconv_benchmark/DNAmDeconv/assets/groups.csv